algo: ppo
env: BabyAI-GoToImpUnlock-v0
model: ~
seed: 1
log_interval: 1
save_interval: 10
procs: 16
frames: 10000000
epochs: 4
batch_size: 256
frames_per_proc: 128
discount: 0.99
lr: 0.001
gae_lambda: 0.95
entropy_coef: 0.01
value_loss_coef: 0.5
max_grad_norm: 0.5
optim_eps: "1e-8"
optim_alpha: 0.99
clip_eps: 0.2
recurrence: 1
text: false
gpt: false
use_trajectory: false
ask_gpt_prob: -1
ask_every: 2000
